---

- name: unzip the artifact.tar.gz
  become: true
  shell: |
    pwd
    tar xvzf ~/artifact.tar.gz -C .
- name: start server
  become: true
  shell: |
    pwd
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start